### ISSUE TITLE
Questions about gaps in outcomes

### ISSUE THREAD

**Issue by czzc22** [ShangwenWang/Cognac#4]
Hello，
I'm sorry to bother you, but I'm having some problems.

I used the data sets you provided: Small, Med and Large to conduct experiments on your model, but the final results were quite different from those in your paper.

I am wondering if I have made some mistakes in parameters. Are the parameters listed in your config file consistent with your experiment at that time? Or is there any code that needs to be uncommented?

I hope you can give me some suggestions so that my reproduction can be as consistent as possible with yours.

Thank you very much for your help.

**Comment by ShangwenWang** [comment]
Hello Thanks for your interest to our work. 
Actually, the values listed in the config.py are just some samples. As we have introduced in the README file, the final values need to be fine-tuned.

The tuning process of our experiment was quite long because it seems quite hard for the model to reach the optimum. Therefore, I guess it is reasonable for you to get different results by directly using the listed parameter values.

**Comment by ShangwenWang** [comment]
Oh I do remember something!
 
In the evaluation, we consider methods with long names as bloated ones and discard such cases. The criterion is whether the number of tokens of a method name exceeds a specific number, which I think is 6. You may use such a setting.
